### ISSUE TITLE
Move current tab to the rightmost

### ISSUE THREAD

**Issue by daicche** [rooa/swaptab#1]
because a new background tab always exists in the rightmost.
A new background tab is related to the current tab usually.

**Comment by rooa** [comment]
Thank you for the suggestion. I will work on that.

**Comment by rooa** [comment]
Implemented `rightmost` command, performed by `Command + Shift + 9`.

**Comment by daicche** [comment]
![](http://lgtm.herokuapp.com/http://l0o0l.co/material/misc/kita-yoshio-delicious_modified2.gif)
