### ISSUE TITLE
If they have pinned tab, the target tab cannot circulate

### ISSUE THREAD

**Issue by daicche** [rooa/swaptab#2]

**Comment by rooa** [comment]
Spotted the same error. I will work out soon.

**Comment by rooa** [comment]
@dai---chi #4 seemed to solve. I will try to publish the extension later.

**Comment by daicche** [comment]
対応はやすぎわろた

**Comment by daicche** [comment]
![](http://lgtm.herokuapp.com/http://pic.prepics-cdn.com/utatan21/11184182.gif)

**Comment by rooa** [comment]
😇

**Comment by daicche** [comment]
あざます 🙇
